<a href="https://colab.research.google.com/github/AgungDaffa/machine/blob/main/week9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Tugas**

Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
Anda diperbolehkan melakukan eksplorasi terhadap,
Metode pra pengolahan
Pemilihan fitur
Arsitektur ANN
Fungsi Aktiviasi
ANN diimplementasikan dengan menggunakan tensorflow.
DIKERJAKAN SECARA BERKELOMPOK
JELASKAN HASIL YANG ANDA DAPATKAN,
AKURASI
CONFUSION MATRIX
KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN


In [1]:

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [2]:

# Pra-pengolahan data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data() # load data MNIST dan split data

# ubah bentuk fitur menjadi vektor dan dinormalisasi
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
# Arsitektur ANN
# Terdiri dari 3 lapisan Dense dengan funsi aktivasi ReLU
ann = keras.Sequential(
    [
        layers.Dense(256, activation="relu"),
        layers.Dense(128, activation="relu"),
        layers.Dense(10),
    ]
)

In [4]:

# Fungsi aktivasi
ann.compile(
    optimizer=keras.optimizers.Adam(0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

In [5]:
# Pelatihan model
# Model dilatih menggunakan data latih dengan batch size 32 dan epoch sebanyak 5 kali.
ann.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

# Evaluasi model
# Model dievaluasi menggunakan data uji dan menghitung akurasi.
test_loss, test_acc = ann.evaluate(x_test, y_test, verbose=2)
print("Test accuracy:", test_acc)

Epoch 1/5
1875/1875 - 14s - loss: 0.2054 - accuracy: 0.9380 - 14s/epoch - 8ms/step
Epoch 2/5
1875/1875 - 12s - loss: 0.0847 - accuracy: 0.9733 - 12s/epoch - 6ms/step
Epoch 3/5
1875/1875 - 9s - loss: 0.0590 - accuracy: 0.9812 - 9s/epoch - 5ms/step
Epoch 4/5
1875/1875 - 9s - loss: 0.0452 - accuracy: 0.9850 - 9s/epoch - 5ms/step
Epoch 5/5
1875/1875 - 10s - loss: 0.0328 - accuracy: 0.9898 - 10s/epoch - 5ms/step
313/313 - 1s - loss: 0.0900 - accuracy: 0.9751 - 788ms/epoch - 3ms/step
Test accuracy: 0.9750999808311462


In [6]:
# Confusion matrix
# Confusion matrix dihitung menggunakan data uji dan prediksi model.
y_pred = ann.predict(x_test)
confusion_matrix = tf.math.confusion_matrix(y_test, tf.argmax(y_pred, axis=1))
print("Confusion matrix:\n", confusion_matrix)

313/313 [==============================] - 2s 6ms/step
Confusion matrix:
 tf.Tensor(
[[ 974    0    0    2    0    1    0    0    1    2]
 [   1 1126    1    3    0    0    1    0    3    0]
 [   6    0 1005    5    3    0    1    6    5    1]
 [   0    0    4  996    0    1    0    3    3    3]
 [   1    0    4    1  957    0    2    1    0   16]
 [   4    0    0   21    2  846   12    0    3    4]
 [   5    3    0    1    6    1  939    0    3    0]
 [   2    2    4    9    1    0    0  989    2   19]
 [   5    0    6    9    6    7    1    3  927   10]
 [   4    2    0    2    7    1    0    0    1  992]], shape=(10, 10), dtype=int32)
